src/nwEventoMVCa.Web/Controllers/CartController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using nwEventoMVCa.Core.Services;
using nwEventoMVCa.Web.Framework;
using nwEventoMVCa.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace nwEventoMVCa.Web.Controllers
{
    [Route("cart")]
    [CookieAuth]
    public class CartController : BaseController
    {
        private readonly ICartService _cartService;
        private readonly IMapper _mapper;

        public CartController(ICartService cartService, IMapper mapper)
        {
            _cartService = cartService;
            _mapper = mapper;
        }

        public IActionResult Index(string returnUrl)
        {
            var cart = _cartService.Get(CurrentUserId);
            if (cart == null)
            {
                _cartService.Create(CurrentUserId);
                cart = _cartService.Get(CurrentUserId);
            }
            var viewModel = _mapper.Map<CartViewModel>(cart);
            viewModel.ReturnUrl = "/products";

            return View(viewModel);
        }

        [HttpPost("{productId}/add")]
        public IActionResult Add(Guid productId, string returnUrl)
        {
            _cartService.AddProduct(CurrentUserId, productId);

            return RedirectToAction(nameof(Index), new { returnUrl });
        }


        [HttpGet("{productId}/delete")]
        public IActionResult Delete(Guid productId)
        {
            _cartService.DeleteProduct(CurrentUserId, productId);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/nwEventoMVCa.Web/Controllers/EventsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using nwEventoMVCa.Core.Domain;
using nwEventoMVCa.Core.DTO;
using nwEventoMVCa.Core.Services;
using nwEventoMVCa.Web.Framework;
using nwEventoMVCa.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nwEventoMVCa.Web.Controllers
{
    [Route("events")]
    [CookieAuth]
    public class EventsController : BaseController
    {
        private readonly IEventService _eventService;
        private readonly ITicketService _ticketService;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;

        public EventsController(IEventService eventService,
           ITicketService ticketService,
           IMapper mapper, IUserService userService)
        {
            _eventService = eventService;
            _ticketService = ticketService;
            _mapper = mapper;
            _userService = userService;
        }

        [AllowAnonymous]
        [HttpGet("{eventPage}")]
        public IActionResult Index(int eventPage)
        {
            var viewModel = new EventListWithPagination()
            {
                EventViewModels = _eventService.GetEventPage(eventPage).Select(e => new EventViewModel(e)),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = eventPage,
                    ItemsPerPage = 4,
                    TotalItems = _eventService.GetAll("").Count()
                },
                CurrentCategory = null
            };
            return View(viewModel);
        }

        [AllowAnonymous]
        [HttpGet("{eventPage}/search")]
        public IActionResult GetAll(int eventPage, string searchString)
        {
            var events = _eventService.GetAll(searchString).Select(e => new EventViewModel(e));
            ViewBag.SearchString = searchString;
            return View(events);
        }

        [HttpGet("{eventPage}/{id}")]
        [Authorize(Policy = "require-admin")]
        public IActionResult Details(Guid id)
        {
            var eventDetails = _eventService.Get(id);
            if (eventDetails == null)
            {
                return NotFound();
            }
            var viewModel = _mapper.Map<EventDetailsViewModel>(eventDetails);

            return View(viewModel);
        }

        [HttpGet("add")]
        [Authorize(Policy = "require-admin")]
        public IActionResult Add()
        {
            var viewModel = new AddOrUpdateEventViewModel();

            return View(viewModel);
        }

        [HttpPost("add")]
        [Authorize(Policy = "require-admin")]
        public IActionResult Add(AddOrUpdateEventViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var eventId = Guid.NewGuid();
            _eventService.Add(eventId, viewModel.Name, viewModel.Category, viewModel.Price);
            _eventService.AddTickets(eventId, viewModel.TicketsCount);

            return RedirectToAction(nameof(Index), new { eventPage = 1});
        }

        [HttpGet("{id}/update/{eventPage}")]
        [Authorize(Policy = "require-admin")]
        public IActionResult Update(Guid id, int  eventPage)
        {
            var @event = _eventService.Get(id);
            if (@event == null)
            {
                return NotFound();
            }
            var viewModel = new AddOrUpdateEventViewModel(@event);

            return View(viewModel);
        }

        [HttpPost("{id}/update/{eventPage}")]
        [Authorize(Policy = "require-admin")]
        public IActionResult Update(AddOrUpdateEventViewModel viewModel, int eventPage)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _eventService.Update(new EventDto
            {
                Id = viewModel.Id,
                Name = viewModel.Name,
                Price = viewModel.Price,
                Category = viewModel.Category
            });

            return RedirectToAction(nameof(Index), new { eventPage });
        }

        [HttpGet("{id}/delete/{eventPage}")]
        [Authorize(Policy = "require-admin")]
        public IActionResult Delete(Guid id, int eventPage)
        {
            _eventService.Delete(id);

            return RedirectToAction(nameof(Index), new { eventPage });
        }

        [HttpPost("{id}/purchase")]
        public IActionResult Purchase(Guid id, int currentEventPage)
        {
            try
            {
                var userDto = _userService.Get(CurrentUserId);
                var email = userDto.Email;
                _ticketService.Purchase(email, id, 1);
                var eventDetailsViewModel = _eventService.Get(id);
                TempData["message"] = $"{eventDetailsViewModel.Name} was added";
                return RedirectToAction(nameof(Index), new { eventPage = currentEventPage });
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        [HttpGet("{id}/cancel")]
        public IActionResult Cancel(Guid id)
        {
            try
            {
                var userDto = _userService.Get(CurrentUserId);
                var email = userDto.Email;
                _ticketService.Cancel(email, id, 1);
                return RedirectToAction("PurchasedEvents", controllerName: "Account");
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

src/nwEventoMVCa.Web/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using nwEventoMVCa.Core.Services;
using nwEventoMVCa.Web.Framework;
using nwEventoMVCa.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nwEventoMVCa.Web.Controllers
{
    [CookieAuth]
    public class OrdersController : BaseController
    {
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper;

        public OrdersController(IOrderService orderService, IMapper mapper)
        {
            _orderService = orderService;
            _mapper = mapper;
        }

        [HttpGet("orders")]
        public IActionResult Index()
        {
            var orders = _orderService.Browse(CurrentUserId);
            var viewModels = _mapper.Map<IEnumerable<OrderViewModel>>(orders);

            return View(viewModels);
        }

        [HttpPost("orders")]
        public IActionResult Create()
        {
            try
            {
                _orderService.Create(CurrentUserId);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

src/nwEventoMVCa.Web/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using nwEventoMVCa.Core.Services;
using nwEventoMVCa.Web.Framework;
using nwEventoMVCa.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nwEventoMVCa.Web.Controllers
{
    [Route("products")]
    [CookieAuth("require-admin")]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            var products = _productService
                .GetAll()
                .Select(p => new ProductViewModel(p));

            return View(products);
        }
    }
}

src/nwEventoMVCa.Web/Views/Shared/_EventSearchBox.cshtml
<form class="" asp-controller="Events" asp-action="GetAll" method="get">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Search event..." 
               name="searchString"  value="@ViewBag.SearchString">
    </div>
</form>

src/nwEventoMVCa.Web/Views/Shared/_EventSummary.cshtml
@using nwEventoMVCa.Core.DTO;
@model EventViewModel
@{
    var isAdmin = User.IsInRole(RoleDto.Admin.ToString());
}
@{
    var id = ViewContext.RouteData.Values["eventPage"];
}

<div class="col-sm-3">
    <div class="btn-group" role="group" style="text-align:center">
        @if (isAdmin)
        {
            <a class="btn btn-primary" asp-action="Update" asp-route-id="@Model.Id" title="Update event">
                <i class="fas fa-edit"></i>
            </a>
        }
        @if (isAdmin)
        {
            <a class="btn btn-info" asp-action="Details" asp-route-id="@Model.Id" title="Details event">
                <i class="fas fa-list-alt"></i>
            </a>
        }
        @if (isAdmin)
        {
            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id" title="Delete event">
                <i class="far fa-trash-alt"></i>
            </a>
        }
    </div>
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />

        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a href="#">@Model.Name</a>
            </h3>
            <p>@Model.Category</p>
            @if (isAdmin)
            {
                <h6 class="card-subtitle mb-2 text-muted">@Model.Id</h6>
                <h6 class="card-subtitle mb-2 text-muted">TicketsCount: @Model.TicketsCount</h6>
            }
            <h6 class="card-subtitle mb-2 text-muted">AvailableTickets: @Model.AvailableTicketsCount</h6>
            <div>
                <form id="@Model.Id" asp-action="purchase"
                      asp-controller="events" asp-route-id="@Model.Id" method="post">
                    <input type="hidden" asp-for="@Model.Id" />
                    <input type="hidden" name="currentEventPage" value="@ViewContext.RouteData.Values["eventPage"]" />
                    <button type="submit" class="btn btn-success">
                        Attend
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

src/nwEventoMVCa.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />

    @*Toast*@
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>*@
    @*My css*@
    @*Awesome fonts*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/my.css" />
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">nwEventoMVCa</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="events" asp-action="Index" asp-route-eventPage="1">Events</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Account" asp-action="PurchasedEvents">My Events</a></li>
                }
                <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Cart" asp-action="Index">My Cart</a></li>
                    <li><a asp-controller="Orders" asp-action="Index">My Orders</a></li>
                    <li>@await Component.InvokeAsync("CartSummary")</li>
                }
            </ul>
            <partial name="_LoginPartial">
            
</div>
    </nav>
    <div class="container body-content">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
    <footer class="container-fluid">
        <p></p>
    </footer>
    
    <script src="~/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>